name: bci-arco-gp
channels:
  - gpytorch
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cpuonly=2.0
  - jupyter=1.0.0
  - matplotlib=3.7.2
  - networkx=3.1
  - numpy=1.24.3
  - pip=23.3
  - python=3.8.18
  - pytorch=2.1.0
  #  - pytorch-cuda=11.8
  - scipy=1.10.1
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - pip:
      - causal-learn==0.1.3.8
      - gadjid==0.0.1
      - gcastle==1.0.3
      - gpytorch==1.11
      - pandas==2.0.3
      - scikit-learn==1.3.2
      - sumu==0.1.2
